### ISSUE TITLE
Unable to load IPython.mathjaxutils

### ISSUE THREAD

**Issue by takluyver** [jupyter/colaboratory#100]
When I create or open a notebook, a popup appears saying "Unable to load the framework.
Error: IPython.mathjaxutils is undefined See console for more details."

The browser console has a traceback:

```
TypeError: IPython.mathjaxutils is undefined
Stack trace:
colab.onLoadNotebookSuccess_@http://127.0.0.1:8844/colab/js/main.js:253:5
loadNotebook/<@http://127.0.0.1:8844/colab/js/main.js:117:7
colab.model.Notebook.prototype.load/onLoadCallback/</xhrRequest.onreadystatechange@http://127.0.0.1:8844/colab/js/model/notebook.js:422:13
```

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
