### ISSUE TITLE
increasing editor font size (Ctrl-M 0) doesn't work in ChromeOS 36

### ISSUE THREAD

**Issue by mr-c** [jupyter/colaboratory#101]
Google Chrome   36.0.1985.143 (Official Build 287914) 
Platform    5841.98.0 (Official Build) stable-channel link
Blink   537.36 (@179211)
JavaScript  V8 3.26.31.15
Flash   14.0.0.177-r1
User Agent  Mozilla/5.0 (X11; CrOS x86_64 5841.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
