### ISSUE TITLE
Markdown hyperlinks should open in new window

### ISSUE THREAD

**Issue by mr-c** [jupyter/colaboratory#102]
Currently they take over the interface. Using the hardware 'back' key on a Chromebook Pixel results in an incompletely loaded interface.
![screenshot 2014-09-05 at 13 55 24](https://cloud.githubusercontent.com/assets/1330696/4169281/d849250a-3525-11e4-8810-03c806890da0.png)

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
