### ISSUE TITLE
Proposal : substitute Google Drive by remoteStorage.

### ISSUE THREAD

**Issue by almereyda** [jupyter/colaboratory#104]
[remotestorage.js](https://github.com/remotestorage/remotestorage.js) allows [self-hosted per-user storage](http://remotestorage.io/).

Please consider it over maintaining a Google Drive integration.
It also takes care of that, including Dropbox.

I am sure @michielbdejong, @galfert and @skddc can give fruitful advice, if only pointers, if needed. There's also a [community discourse](http://community.remotestorage.io/).

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
