### ISSUE TITLE
Show output and return values differently (just a tweak)

### ISSUE THREAD

**Issue by dsblank** [jupyter/colaboratory#108]
Overall, I prefer the colaboratory UI to the IPython one. Good job! (Perhaps there are some aspects that can be applied there.)

But, as a CS educator, it is difficult to get students to realize the distinction between return values and printed output (side-effects). Colaboratory appears to blur the distinction. It would be great if the return value was marked in an obvious manner. This would also include non-textual outputs. Thanks!

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
