### ISSUE TITLE
Ongoing maintenance of browser extension - pandas updates?

### ISSUE THREAD

**Issue by psychemedia** [jupyter/colaboratory#109]
I was wondering what sort of ongoing support or maintenance, if any, this project is likely to have, particularly in respect of the Chrome app?

For example, pandas had a recent update, which presumably means that the new version needs to be compiled for NaCl for use in the Chrome extension?

I'm looking at using the Chrome extension in the context of a MOOC, as it provides an alternative to complex IPython installs on learners' own computers, or cost'n'admin requirements arising from remote hosting. It would be useful to know if the extension in particular is frozen in it's development or whether the project is still open?

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
