### ISSUE TITLE
Start IPy NB: Ends up ImportError: No Module Named Log

### ISSUE THREAD

**Issue by asinode** [jupyter/colaboratory#112]
While following the [README](https://github.com/jupyter/colaboratory/), I encountered this `ImportError` at the step that says **Start IPython notebook:**
`$ python -m colaboratory`
`Traceback (most recent call last):`
`File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main`
`"__main__", fname, loader, pkg_name)`
`File "/usr/lib/python2.7/runpy.py", line 72, in _run_code`
`exec code in run_globals`
`File "/wine/Programming 10Aug2014/Python Aug 2013/python_9oct14/Works_Office29d14/6f15/colaboratory/colaboratory/__main__.py", line 9, in <module>`
`from colaboratory import launch_new_instance`
`File "colaboratory/colaboratory.py", line 51, in <module>`
`from IPython.html.log import log_request`
`ImportError: No module named log`

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
