### ISSUE TITLE
Stopping at PNaCl initializing step

### ISSUE THREAD

**Issue by SuvroB** [jupyter/colaboratory#116]
HI,

After I launch the colaboratory app from my Chromebook, it is not getting connected to the kernel.
It gets stuck at the PNaCl initializing step. It was working fine all these days, but suddenly has stopped working. Please help.

Thanks
Suvro

**Comment by KesterTong** [comment]
Hi @SuvroB, can you let me know which version of Chrome OS you are using, and if this problem started occurring after upgrading to a new version of Chrome OS?

**Comment by SuvroB** [comment]
Hi, thanks for your quick response. The Chrome OS version I am using is 41.0.2272.89 and the platform is 6680.64.0. Not sure if there had been a version update recently but I remember there was some update a few days ago. 
It also says your device is up to date.

Thanks
Suvro

**Comment by SuvroB** [comment]
Hi Kester, - any suggestion ?
Thanks
Suvro

**Comment by KesterTong** [comment]
Hi, I'm still looking for a machine to replicate this error.  I will try to have it done by the end of the week.  In the meantime, are you able to give me the output from the javascript console?

**Comment by SuvroB** [comment]
Hi, its an installed drive application and does not run on the browser. Will I be still able to generate the log from the javascript console ? Or are there other ways to generate the application log? I am not aware of it. Thanks.

**Comment by KesterTong** [comment]
I think it is still possible but I don't have a Chromebook handy to give instructions.  It might require switching on some kind of developers mode.

**Comment by SuvroB** [comment]
I uninstalled it & tried to install it back and it gives an error "Package is invalid: Could not unzip extension". Attaching the JavaScript console message.

XHR finished loading: POST "https://chrome.google.com/webstore/ajax/eventlog?hl=en-US&gl=US&pv=20141016â€¦%2Caph%2Cigb%2Cpot%2Cgrt%2Crma%2Cshr%2Chls%2Crer%2Cpet&_reqid=1446368&rt=j".webstore.js:382 tt.sendwebstore.js:425 g.Anwebstore.js:412 Dvwebstore.js:411 yvwebstore.js:408 vv.sendwebstore.js:398 Qu.sendwebstore.js:469 fpwebstore.js:313 dpwebstore.js:313 (anonymous function)webstore.js:246 Sjwebstore.js:244 g.Gwebstore.js:261 g.Nswebstore.js:378 c
webstore.js:382 XHR finished loading: POST "https://chrome.google.com/webstore/ajax/eventlog?hl=en-US&gl=US&pv=20141016â€¦%2Caph%2Cigb%2Cpot%2Cgrt%2Crma%2Cshr%2Chls%2Crer%2Cpet&_reqid=1546368&rt=j".webstore.js:382 tt.sendwebstore.js:425 g.Anwebstore.js:412 Dvwebstore.js:411 yvwebstore.js:408 vv.sendwebstore.js:398 Qu.sendwebstore.js:469 fpwebstore.js:313 dpwebstore.js:313 (anonymous function)webstore.js:246 Sjwebstore.js:244 g.Gwebstore.js:261 g.Nswebstore.js:378 c
webstore.js:382 XHR finished loading: POST "https://chrome.google.com/webstore/ajax/eventlog?hl=en-US&gl=US&pv=20141016â€¦%2Caph%2Cigb%2Cpot%2Cgrt%2Crma%2Cshr%2Chls%2Crer%2Cpet&_reqid=1646368&rt=j".webstore.js:382 tt.sendwebstore.js:425 g.Anwebstore.js:412 Dvwebstore.js:411 yvwebstore.js:408 vv.sendwebstore.js:398 Qu.sendwebstore.js:469 fpwebstore.js:313 dpwebstore.js:313 (anonymous function)webstore.js:246 Sjwebstore.js:244 g.Gwebstore.js:261 g.Nswebstore.js:378 c
webstore.js:382 XHR finished loading: POST "https://chrome.google.com/webstore/ajax/eventlog?hl=en-US&gl=US&pv=20141016â€¦%2Caph%2Cigb%2Cpot%2Cgrt%2Crma%2Cshr%2Chls%2Crer%2Cpet&_reqid=1746368&rt=j".webstore.js:382 tt.sendwebstore.js:425 g.Anwebstore.js:412 Dvwebstore.js:411 yvwebstore.js:408 vv.sendwebstore.js:398 Qu.sendwebstore.js:469 fpwebstore.js:313 dpwebstore.js:313 (anonymous function)webstore.js:246 Sjwebstore.js:244 g.Gwebstore.js:261 g.Nswebstore.js:378 c
webstore.js:382 XHR finished loading: POST "https://chrome.google.com/webstore/ajax/login-state?hl=en-US&gl=US&pv=20141â€¦%2Caph%2Cigb%2Cpot%2Cgrt%2Crma%2Cshr%2Chls%2Crer%2Cpet&_reqid=1846368&rt=j".webstore.js:382 tt.sendwebstore.js:425 g.Anwebstore.js:412 Dvwebstore.js:411 yvwebstore.js:408 vv.sendwebstore.js:398 Qu.sendwebstore.js:480 by.Jawebstore.js:378 c
webstore.js:382 XHR finished loading: POST "https://chrome.google.com/webstore/ajax/eventlog?hl=en-US&gl=US&pv=20141016â€¦%2Caph%2Cigb%2Cpot%2Cgrt%2Crma%2Cshr%2Chls%2Crer%2Cpet&_reqid=1946368&rt=j".webstore.js:382 tt.sendwebstore.js:425 g.Anwebstore.js:412 Dvwebstore.js:411 yvwebstore.js:408 vv.sendwebstore.js:398 Qu.sendwebstore.js:469 fpwebstore.js:313 dpwebstore.js:313 (anonymous function)webstore.js:246 Sjwebstore.js:244 g.Gwebstore.js:261 g.Nswebstore.js:378 c

**Comment by SuvroB** [comment]
Hi Kester, Any updates ? Thanks.

**Comment by KesterTong** [comment]
Hi @SuvroB, I was unable to reproduce either error using a Chromebook with chrome version  41.0.2272.89  and platform 6680.64.0 (same as yours).

I wonder if there is some other issue?  If your zip is "invalid" I wonder if it means that some security key has changed and so your system is marking the contents as invalid?

When does the error occur?  Are you able to install anything else off the web store?

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
