### ISSUE TITLE
Security issue blocking runs?

### ISSUE THREAD

**Issue by chrism71** [jupyter/colaboratory#117]
When trying to run my code, the browser reports:
"Some cells were modified outside this session. For security reasons, please run this notebook manually first."

I'm not sure what this means, nor how to get past it. I thought it might be browser related, so I cleared everything out, but the error persists. I've restarted the kernel, but that is not reporting any issues.

Thanks for any assistance.

**Comment by KesterTong** [comment]
Is it only on particular document, or all documents?  And have you recently switched users, or do you have multiple users/identities logged in with Google/Chrome?

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
