### ISSUE TITLE
When trying "share" option "no apps with 26410270374 id" message appears

### ISSUE THREAD

**Issue by magdalenat** [jupyter/colaboratory#121]

**Comment by RomainBui** [comment]
same issue

**Comment by wenjinshao** [comment]
FWIW a workaround is to share from Google Drive. (Right-click the .ipynb file in Drive, and choose "Share".)

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
