### ISSUE TITLE
Are there other alternatives to google drive? 

### ISSUE THREAD

**Issue by jackiekazil** [jupyter/colaboratory#123]
Are their other alternatives (like OneDrive) to google drive or plans for them? I ask, because not everyone has access to Google drive in their organizations to be able to use this and getting a new tool approved in places like an government Agency can be difficult -- this is where some folks will sometimes give up on a tool.

The other possible solution is Dropbox, but Dropbox is often blocked, so that wouldn't be a solution for the cases that I am talking about.

**Comment by rgbkrk** [comment]
At some point, I'll probably hack on a RethinkDB based store which you could run internally. No promises though, just something I've been thinking on. If there are folks willing to fund such a thing, @captainsafia and others would love to collaborate on this.

**Comment by rgbkrk** [comment]
Also, if you just want storage (not the realtime aspect), you can also use a content store like these:

* [Postgres contents](https://github.com/quantopian/pgcontents)
* [OpenStack Swift store](https://github.com/rgbkrk/bookstore) - note: not up to date, welcome to new maintainers

**Comment by jackiekazil** [comment]
Was looking for the realtime. :-) 
Ty for the response. 
(Feel free to close this ticket.)

**Comment by rgbkrk** [comment]
Thanks for bringing that up! My head was buried in the sand, thinking of what it would be like to run something on-site for a government agency or lab that didn't want to reach out to the wider web.

**Comment by jackiekazil** [comment]
@rgbkrk let me know if you ever want to chat more about this. I can put you in touch with folks that can give you more distinct use cases and talk through the issue. My email is my user name at google's mail server.

**Comment by slel** [comment]
Note that in addition to using SageMathCloud at https://cloud.sagemath.com/,
any person or group can run their own instance of SageMathCloud.

Some relevant recent mailing list threads about that:

  - SageMathCloud docker image
    sage-cloud post by William Stein, 2016-08-22
    https://groups.google.com/d/topic/sage-cloud/S9WqlcaZ_9k/discussion

  - SageMathCloud customized institutional setup
    sage-cloud post by Robert Lowe, 2016-08-26
    https://groups.google.com/d/topic/sage-cloud/og3tmsXK-K0/discussion
