### ISSUE TITLE
up to date source code

### ISSUE THREAD

**Issue by FalseProtagonist** [jupyter/colaboratory#128]
This has been abandoned development, and gives a link to the Google project. I can't find source code for that project, is it closed-source now or am I just failing at finding it?

A link to the source code or a clarification that it's now closed source might be nice for anyone else with the same question.

**Comment by rgbkrk** [comment]
Google colab is a (mostly) closed source project, though they're open sourcing more and more here: https://github.com/googlecolab

/cc @craigcitro
