### ISSUE TITLE
Confusion in the execution model while working collaboratively

### ISSUE THREAD

**Issue by fperez** [jupyter/colaboratory#22]
Right now, when two or more users are editing a single notebook collaboratively, the result can be quite confusing when execution is also mixed in: everyone _sees_ a single, common output view, but that view is really the mix of the states of everybody's kernels.

The end-user experience can be quite confusing.

We'll need to sort out a simpler execution model, perhaps with an 'execution baton' that can be passed from one user to another but can only be held by one person at a time.

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
