### ISSUE TITLE
Some drive functionality doesn't work when mixing http and https

### ISSUE THREAD

**Issue by kayur** [jupyter/colaboratory#38]
When running on the local server and trying to share, I get this error: 

<pre> 
Refused to display 'https://drive.google.com/share?id=0B0T... in a frame 
because it set 'X-Frame-Options' to 'SAMEORIGIN'.
</pre>

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
