### ISSUE TITLE
Delete Cloud Console Project containing old Client IDs

### ISSUE THREAD

**Issue by KesterTong** [jupyter/colaboratory#5]
Previously we were using client IDs in a different project from Google's internal build.  However this caused realtime API conflicts, so all Client IDs are now moved into the same project as the one used by Google's internal build.
Deleting the project containing the old Client IDs will cause any forks using the old Client IDs to stop working, but will prevent any further realtime conflicts

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
