### ISSUE TITLE
Basic bokeh support via output_notebook()

### ISSUE THREAD

**Issue by standarddeviant** [jupyter/colaboratory#55]
When trying to execute this in a cell:
from bokeh.plotting import *
output_notebook()
## I get this:

RuntimeError                              Traceback (most recent call last)
<ipython-input-12-547b64dbc8f2> in <module>()
      1 from bokeh.plotting import *
----> 2 output_notebook()

/home/dave/anaconda/lib/python2.7/site-packages/bokeh/plotting.pyc in output_notebook(url, docname, session, name)
    155     else:
    156         from . import load_notebook
--> 157         load_notebook()
    158     global _default_notebook
    159     _default_notebook = True

/home/dave/anaconda/lib/python2.7/site-packages/bokeh/**init**.pyc in load_notebook(resources, verbose, force, skip)
     36             pass
     37         if not notebook:
---> 38             raise RuntimeError('load_notebook() only works inside an IPython Notebook.')
     39 
     40     import IPython.core.displaypub as displaypub

RuntimeError: load_notebook() only works inside an IPython Notebook.

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
