### ISSUE TITLE
Installation fails on Samsung (ARM) Chromebook

### ISSUE THREAD

**Issue by glinden** [jupyter/colaboratory#78]
If you attempt to install the Chrome app

https://chrome.google.com/webstore/detail/colaboratory-notebook/pianggobfjcgeihlmfhfgkfalopndooo

using a Samsung ARM Chromebook, it appears the installation repeatedly fails with the error "package invalid, could not unzip extension".

As students increasingly are working on Chromebooks, it would be desirable to have this working on Chromebooks.  If that is difficult (due to ARM support or any other reason), the app maybe should be disabled for Chromebooks (or at least a warning put on the app installation page about lack of Chromebook support).

Definitely would appreciate it if someone could try to repro using a ARM Chromebook and non-ARM Chromebook to confirm the error is a general issue and determine the scope of the issue, thanks.

**Comment by andmalc** [comment]
Runs OK on my Samsung Series 3 ARM Chromebook

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
