### ISSUE TITLE
Handle "Fatal Realtime API Error", warn on large notebooks

### ISSUE THREAD

**Issue by probablyrgbkrk** [jupyter/colaboratory#79]
Just set up colaboratory on a fresh Google profile, uploaded a notebook to drive. After some time, I end up getting this error message:

```
Fatal Realtime API Error
The realtime API gave the following error: Open compound operation at end of synchronous block - did you forget to call endCompoundOperation()?. You must reload this document.
```

![screen shot 2014-08-08 at 8 40 44 pm](https://cloud.githubusercontent.com/assets/8367437/3864948/fa7dcf6e-1f76-11e4-8279-2bb2611ebb04.png)

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
