### ISSUE TITLE
PNaCl kernel refactoring

### ISSUE THREAD

**Issue by KesterTong** [jupyter/colaboratory#87]
Note: this concerns code that will be committed to naclports, not this repo.

The current version of kernel.py is based on overriding certain classes defined by IPython.  However, this is done in a very messy way that requires duplicating a lot of IPython code.

A much cleaner approach would be to subclass the IPython.kernel.zmq.Session and create alternative implementations of zmq.eventloop.zmqstream.ZMQStream and zmq.Socket.

@MatthewTurk You probably know more about zmq, while I'm more familiar with the IPython internals.  What do the ZMQStream and zmq.Socket classes look like?  Are they trivial to override or does their public interface include ZMQ specific things?

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
