### ISSUE TITLE
Help with question mark hangs NaCL

### ISSUE THREAD

**Issue by ilblackdragon** [jupyter/colaboratory#88]
Enter and execute: `import numpy`
In second cell: `numpy.array?` and press Ctrl+Enter.
NaCL is hanging. Interrupt doesn't work either.

Output in a console:

```
nacl>Function popen is not implemented in glibc-compat, aborting!
 pnacl_kernel.js:92
```

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
