### ISSUE TITLE
Enable shell in PNaCl kernel

### ISSUE THREAD

**Issue by MatthewTurk** [jupyter/colaboratory#91]
Recent modifications to naclports have enabled subprocess in Python.  We should be able to enable Jupyter notebook shell magic in PNaCl if we properly support this.  However, we're going to be limited by the size of our distribution, which we've started trimming; including more executables makes this more interesting, but pushes the required memfs size up.

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
