### ISSUE TITLE
add border to icon

### ISSUE THREAD

**Issue by mr-c** [jupyter/colaboratory#99]
In CrOS the icon background is black when windows are fullscreen
![screenshot 2014-08-28 at 13 47 20](https://cloud.githubusercontent.com/assets/1330696/4074396/d9d2e2e8-2ea0-11e4-9252-9d9961ba0730.png)
The black icon without a border doesn't show up too well against the desktop wallpaper either.
![screenshot 2014-08-28 at 13 46 58](https://cloud.githubusercontent.com/assets/1330696/4074397/d9f061a6-2ea0-11e4-9f9b-ff06d763cabc.png)

**Comment by rgbkrk** [comment]
This version of colaboratory is no longer supported, please switch to https://colab.research.google.com.
